/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as PersonagensIndexRouteImport } from './routes/personagens/index'
import { Route as PersonagensIdRouteImport } from './routes/personagens/$id'
import { Route as ProducoesIndexRouteImport } from './routes/producoes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'
import { Route as ProdutosIdRouteImport } from './routes/produtos/$id'
import { Route as ProdutosNovoRouteImport } from './routes/produtos/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensIndexRoute = PersonagensIndexRouteImport.update({
  id: '/personagens/',
  path: '/personagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensIdRoute = PersonagensIdRouteImport.update({
  id: '/personagens/$id',
  path: '/personagens/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducoesIndexRoute = ProducoesIndexRouteImport.update({
  id: '/producoes/',
  path: '/producoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIdRoute = ProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosNovoRoute = ProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/personagens/$id': typeof PersonagensIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/personagens/': typeof PersonagensIndexRoute
  '/producoes/': typeof ProducoesIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/personagens/$id': typeof PersonagensIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/personagens': typeof PersonagensIndexRoute
  '/producoes': typeof ProducoesIndexRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/personagens/$id': typeof PersonagensIdRoute
  '/produtos/$id': typeof ProdutosIdRoute
  '/produtos/novo': typeof ProdutosNovoRoute
  '/personagens/': typeof PersonagensIndexRoute
  '/producoes/': typeof ProducoesIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/personagens/$id'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/personagens/'
    | '/producoes/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/personagens/$id'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/personagens'
    | '/producoes'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/personagens/$id'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/personagens/'
    | '/producoes/'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  PersonagensIdRoute: typeof PersonagensIdRoute
  ProdutosIdRoute: typeof ProdutosIdRoute
  ProdutosNovoRoute: typeof ProdutosNovoRoute
  PersonagensIndexRoute: typeof PersonagensIndexRoute
  ProducoesIndexRoute: typeof ProducoesIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens/': {
      id: '/personagens/'
      path: '/personagens'
      fullPath: '/personagens/'
      preLoaderRoute: typeof PersonagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens/$id': {
      id: '/personagens/$id'
      path: '/personagens/$id'
      fullPath: '/personagens/$id'
      preLoaderRoute: typeof PersonagensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producoes/': {
      id: '/producoes/'
      path: '/producoes'
      fullPath: '/producoes/'
      preLoaderRoute: typeof ProducoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$id': {
      id: '/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof ProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/novo': {
      id: '/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof ProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  PersonagensIdRoute: PersonagensIdRoute,
  ProdutosIdRoute: ProdutosIdRoute,
  ProdutosNovoRoute: ProdutosNovoRoute,
  PersonagensIndexRoute: PersonagensIndexRoute,
  ProducoesIndexRoute: ProducoesIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
