/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCenariosIndexRouteImport } from './routes/_authenticated/cenarios/index'
import { Route as AuthenticatedPersonagensIndexRouteImport } from './routes/_authenticated/personagens/index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos/index'
import { Route as AuthenticatedProdutosIdRouteImport } from './routes/_authenticated/produtos/$id'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos/novo'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos/index'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated/projetos/$id'
import { Route as AuthenticatedProjetosNovoRouteImport } from './routes/_authenticated/projetos/novo'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCenariosIndexRoute =
  AuthenticatedCenariosIndexRouteImport.update({
    id: '/cenarios/',
    path: '/cenarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonagensIndexRoute =
  AuthenticatedPersonagensIndexRouteImport.update({
    id: '/personagens/',
    path: '/personagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIdRoute = AuthenticatedProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosNovoRoute =
  AuthenticatedProjetosNovoRouteImport.update({
    id: '/projetos/novo',
    path: '/projetos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/cenarios/': typeof AuthenticatedCenariosIndexRoute
  '/personagens/': typeof AuthenticatedPersonagensIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/cenarios': typeof AuthenticatedCenariosIndexRoute
  '/personagens': typeof AuthenticatedPersonagensIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/_authenticated/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/_authenticated/cenarios/': typeof AuthenticatedCenariosIndexRoute
  '/_authenticated/personagens/': typeof AuthenticatedPersonagensIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/cenarios/'
    | '/personagens/'
    | '/produtos/'
    | '/projetos/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/produtos/$id'
    | '/produtos/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/cenarios'
    | '/personagens'
    | '/produtos'
    | '/projetos'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/produtos/$id'
    | '/_authenticated/produtos/novo'
    | '/_authenticated/projetos/$id'
    | '/_authenticated/projetos/novo'
    | '/_authenticated/cenarios/'
    | '/_authenticated/personagens/'
    | '/_authenticated/produtos/'
    | '/_authenticated/projetos/'
    | '/_authenticated/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cenarios/': {
      id: '/_authenticated/cenarios/'
      path: '/cenarios'
      fullPath: '/cenarios/'
      preLoaderRoute: typeof AuthenticatedCenariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personagens/': {
      id: '/_authenticated/personagens/'
      path: '/personagens'
      fullPath: '/personagens/'
      preLoaderRoute: typeof AuthenticatedPersonagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/$id': {
      id: '/_authenticated/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AuthenticatedProdutosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/novo': {
      id: '/_authenticated/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof AuthenticatedProjetosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProdutosIdRoute: typeof AuthenticatedProdutosIdRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRoute
  AuthenticatedProjetosNovoRoute: typeof AuthenticatedProjetosNovoRoute
  AuthenticatedCenariosIndexRoute: typeof AuthenticatedCenariosIndexRoute
  AuthenticatedPersonagensIndexRoute: typeof AuthenticatedPersonagensIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProdutosIdRoute: AuthenticatedProdutosIdRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRoute,
  AuthenticatedProjetosNovoRoute: AuthenticatedProjetosNovoRoute,
  AuthenticatedCenariosIndexRoute: AuthenticatedCenariosIndexRoute,
  AuthenticatedPersonagensIndexRoute: AuthenticatedPersonagensIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
