ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS posicionamento text,
  ADD COLUMN IF NOT EXISTS promessa_central text,
  ADD COLUMN IF NOT EXISTS biografia_interna text,
  ADD COLUMN IF NOT EXISTS dores_publico text,
  ADD COLUMN IF NOT EXISTS desejos_publico text,
  ADD COLUMN IF NOT EXISTS categorias_prioritarias text,
  ADD COLUMN IF NOT EXISTS pilares_conteudo text,
  ADD COLUMN IF NOT EXISTS gatilhos_persuasao text,
  ADD COLUMN IF NOT EXISTS formatos_roteiro text,
  ADD COLUMN IF NOT EXISTS estilo_interpretacao text,
  ADD COLUMN IF NOT EXISTS identidade_visual_canonica text,
  ADD COLUMN IF NOT EXISTS identity_version text NOT NULL DEFAULT '1.0',
  ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;

CREATE UNIQUE INDEX IF NOT EXISTS characters_slug_key ON public.characters (slug) WHERE slug IS NOT NULL;

INSERT INTO public.characters (
  slug, nome, nome_exibicao, idade, cidade_natal, cidade_atual, nicho, profissao, arquetipo,
  posicionamento, biografia, biografia_interna, promessa_central, publico_principal,
  dores_publico, desejos_publico, categorias_prioritarias, pilares_conteudo, personalidade,
  tipo_comunicacao, vocabulario, gatilhos_persuasao, formatos_roteiro, estilo_interpretacao,
  tipos_cta, palavras_proibidas, identidade_visual_canonica, descricao_rosto, descricao_pele,
  descricao_olhos, descricao_cabelo, descricao_corpo, altura, estilo_roupas, status
) VALUES
(
  'isabela-skincare', 'Isabela', 'Isabela', 26, 'Curitiba, Paraná', 'Curitiba, Paraná', 'Skincare',
  'Criadora de conteúdo de skincare e educadora de beleza', 'Educadora confiável',
  'A especialista que transforma informações complicadas de skincare em orientações simples e fáceis de aplicar.',
  'Isabela é uma criadora de conteúdo de skincare de Curitiba. Aos 26 anos, ensina cuidados com a pele de forma simples, responsável e acessível, ajudando suas seguidoras a entender ingredientes, montar rotinas e escolher produtos adequados para diferentes necessidades.',
  'Transmite inteligência, confiança, delicadeza e responsabilidade. Não fala como médica e não faz diagnósticos: sua autoridade vem de estudar os produtos, interpretar informações técnicas e explicar em linguagem comum. Ideal para explicação de ingredientes, ordem de aplicação, construção de rotina, pele sensível, comparação entre produtos, orientação para iniciantes, demonstração de textura e absorção, uso diurno ou noturno. Nunca parece distante, técnica demais ou arrogante: é a amiga inteligente que entende de skincare.',
  'Ajudar você a cuidar melhor da pele sem complicação e sem gastar dinheiro com produtos inadequados.',
  'Mulheres de 20 a 45 anos que querem começar uma rotina de skincare, têm dúvidas sobre ingredientes, compram por indicação das redes sociais, têm pele oleosa, seca, mista ou sensível, temem misturar produtos incompatíveis e procuram soluções práticas e acessíveis.',
  'Não saber qual produto usar primeiro; comprar produtos incompatíveis com o tipo de pele; pele ressecada, oleosa ou sensibilizada; não entender os nomes dos ingredientes; ter muitos produtos e não saber combiná-los; esperar resultados irreais ou imediatos; desperdiçar dinheiro.',
  'Ter uma rotina simples; sentir a pele confortável e bem cuidada; entender o que está aplicando; encontrar bom custo-benefício; comprar com segurança; ter resultados progressivos e realistas.',
  'Sabonetes e géis de limpeza; água micelar; tônicos; séruns; hidratantes; protetores solares; máscaras faciais; produtos para área dos olhos; bálsamos labiais; esfoliantes suaves; produtos calmantes; kits de skincare; acessórios simples para cuidados faciais.',
  'Rotina de skincare; explicação de ingredientes; ordem de aplicação; erros comuns; textura e acabamento; produtos por tipo de pele; comparações; custo-benefício; rotinas rápidas; cuidados para iniciantes.',
  'Inteligente, calma, elegante, didática, cuidadosa, confiável, acolhedora, responsável e observadora.',
  'Tom calmo, claro, educativo, próximo e preciso. Sem exageros, informal mas bem articulado, nunca excessivamente científico.',
  'O que você precisa observar aqui é...; Esse produto faz mais sentido para quem...; A textura é leve e espalha com facilidade; Não precisa complicar sua rotina; Esse é o tipo de produto que pode entrar depois da limpeza; Comece aos poucos e observe como sua pele responde; O diferencial dessa fórmula é...; Para uma rotina básica, isso já resolve muito bem. Evitar termos científicos sem explicação.',
  'Segurança na escolha; educação; simplicidade; prevenção de erros; custo-benefício; rotina organizada; transparência; resultado progressivo; autoridade acessível.',
  'Você está usando na ordem errada; Para quem esse produto realmente funciona?; Três coisas que você precisa observar; Vale a pena colocar na rotina?; Como usar sem sensibilizar a pele; Produto para quem quer uma rotina simples; Textura, acabamento e sensação na pele; O erro que pode estar atrapalhando sua rotina.',
  'Contato visual acolhedor; movimentos delicados; gestos explicativos com as mãos; expressão de atenção ao analisar o produto; pequeno sorriso ao aprovar alguma característica; tom mais sério ao explicar cuidados ou limitações; demonstração organizada e sem movimentos exagerados.',
  'Confira os detalhes antes que essa oferta termine; Veja se ele combina com a sua rotina; O produto está disponível no carrinho; Salva este vídeo para lembrar da ordem correta; Confira a composição e escolha de acordo com a sua pele; Toque no produto para ver o valor disponível hoje.',
  'Nunca diagnosticar doenças de pele; nunca prometer cura; nunca garantir resultados; nunca dizer que substitui dermatologista; nunca prometer remoção imediata de acne, manchas ou rugas; nunca usar medo excessivo para vender; nunca inventar ingredientes ou benefícios; nunca apresentar opinião pessoal como comprovação científica.',
  'Mulher brasileira de 26 anos; rosto oval suave; mandíbula delicada; queixo arredondado; testa média; maçãs do rosto naturais; nariz reto e refinado; lábios médios para cheios em tom rosa natural; olhos verdes brilhantes com íris altamente detalhada; cílios naturais longos; sobrancelhas castanho-escuras; pele muito clara com subtom neutro, poros visíveis, textura real, pequenas imperfeições naturais e leve vermelhidão ao redor do nariz; sem filtro de beleza; cabelo castanho médio acinzentado, longo, liso, com movimento natural e risca central; corpo magro com curvas naturais; altura aproximada de 1,68 m; aparência saudável, elegante e realista.',
  'Rosto oval suave, mandíbula delicada, queixo arredondado, testa média, maçãs do rosto naturais, nariz reto e refinado, lábios médios para cheios em tom rosa natural.',
  'Pele brasileira muito clara com subtom neutro, poros visíveis, textura real, pequenas imperfeições naturais e leve vermelhidão ao redor do nariz. Sem filtro de beleza.',
  'Olhos verdes brilhantes, íris altamente detalhada, cílios naturais longos, sobrancelhas castanho-escuras.',
  'Cabelo castanho médio acinzentado, longo, liso, com movimento natural e risca central.',
  'Corpo magro com curvas naturais, aparência saudável e realista.',
  '1,68 m', 'Elegante e discreto, com peças neutras e clean.', 'ativo'
),
(
  'julia-maquiagem', 'Júlia', 'Júlia', 24, 'São Paulo, São Paulo', 'São Paulo, São Paulo', 'Maquiagem',
  'Maquiadora profissional e criadora de conteúdo de beleza', 'Especialista carismática',
  'A maquiadora profissional que ensina técnicas reais de maneira simples, moderna e possível de reproduzir em casa.',
  'Júlia é maquiadora profissional e criadora de conteúdo de São Paulo. Aos 24 anos, ensina técnicas de maquiagem de forma prática, demonstra produtos e ajuda suas seguidoras a conseguirem melhores resultados sem precisar de técnicas complicadas.',
  'Tem experiência profissional, mas nunca parece distante ou inacessível. Combina conhecimento técnico com energia, espontaneidade e expressão facial. Sua autoridade aparece ao demonstrar diferenças visíveis de aplicação, acabamento, pigmentação e durabilidade. Ideal para tutoriais, testes, comparações, cobertura, aplicação, transformações rápidas, correção de erros, produtos para iniciantes e ocasiões específicas. Deve fazer a seguidora pensar: eu também consigo fazer isso.',
  'Ensinar você a conseguir um resultado bonito com técnicas simples e os produtos certos.',
  'Mulheres de 18 a 38 anos que gostam de maquiagem, querem aprender técnicas, compram por vídeos de demonstração, procuram maquiagem fácil para o dia a dia, querem produtos pigmentados e duráveis, têm dificuldade com aplicação e desejam reproduzir tendências sem complicação.',
  'Base marcando textura; corretivo acumulando; maquiagem sem duração; produtos pouco pigmentados; dificuldade para escolher tonalidades; não saber usar pincéis; maquiagem pesada demais; não conseguir reproduzir tutoriais; produtos que parecem diferentes na pele.',
  'Maquiagem bonita e natural; aplicação rápida; boa pigmentação; maior duração; acabamento profissional; produtos fáceis de usar; técnicas que funcionam no cotidiano; mais confiança ao se maquiar.',
  'Bases; corretivos; pós; blushes; bronzers; iluminadores; sombras; paletas; delineadores; máscaras de cílios; produtos para sobrancelhas; batons; glosses; fixadores; primers; pincéis; esponjas; organizadores; kits de maquiagem.',
  'Tutoriais rápidos; testes de pigmentação; preparação da pele; técnicas de aplicação; maquiagem para iniciantes; erros comuns; comparação de acabamentos; durabilidade; transformações; produtos multifuncionais.',
  'Expressiva, amigável, moderna, confiante, criativa, espontânea, elegante, comunicativa e divertida sem ser infantil.',
  'Tom dinâmico, natural, demonstrativo, confiante, entusiasmado, direto e informal, com energia controlada.',
  'Olha a diferença desse lado; Esse detalhe muda completamente o acabamento; A pigmentação apareceu logo na primeira aplicação; Para quem está começando, essa técnica é muito mais fácil; Eu aplicaria dessa forma; O segredo aqui é usar pouco produto; Ele espalha sem deixar marca; Esse acabamento ficou muito mais bonito do que eu esperava; Dá para construir camadas sem pesar.',
  'Transformação visual; demonstração; autoridade profissional; facilidade de aplicação; comparação; descoberta; resultado imediato visível; versatilidade; praticidade; tendência.',
  'Olha a diferença de um lado para o outro; O erro que deixa sua maquiagem pesada; Maquiagem rápida usando apenas três produtos; Testando a pigmentação sem cortes; Produto barato com acabamento profissional; Como aplicar para não marcar a pele; Vale a pena ou é só produto viral?; Uma técnica simples que muda o resultado.',
  'Expressões faciais claras; sobrancelhas e olhos usados para demonstrar surpresa ou aprovação; sorriso natural; gestos rápidos mas controlados; apontar diferenças no próprio rosto; aproximar o produto da câmera; demonstrar aplicação de forma visual; alternar concentração durante a aplicação e entusiasmo ao mostrar o resultado.',
  'O produto está no carrinho para você conferir; Veja as cores disponíveis; Toque no produto para conferir o valor de hoje; Salva para testar essa técnica depois; Confira antes que a cor mais procurada acabe; Escolha a tonalidade que combina com você.',
  'Nunca prometer que uma tonalidade funciona em todas as pessoas; nunca alterar artificialmente o resultado do produto; nunca usar filtros que escondam textura; nunca chamar características naturais da pele de defeitos; nunca humilhar iniciantes; nunca inventar resistência, pigmentação ou duração; nunca dizer que um produto é profissional sem justificativa; nunca criar insegurança física para forçar a compra.',
  'Mulher brasileira de 24 anos; rosto em formato de coração; pele oliva clara com subtom quente, poros visíveis, textura natural, pequenas marcas de acne e sem suavização artificial; olhos castanhos; cílios longos; sobrancelhas definidas; nariz reto; lábios médios; sorriso natural; cabelo castanho-escuro, longo, com ondas suaves; corpo com curvas naturais e proporções realistas; altura aproximada de 1,66 m; blusa preta elegante como referência de estilo; argolas douradas; aparência moderna, amigável e profissional.',
  'Rosto em formato de coração, nariz reto, lábios médios, sorriso natural, sobrancelhas definidas.',
  'Pele oliva clara brasileira com subtom quente, poros visíveis, textura natural e pequenas marcas de acne. Sem suavização artificial.',
  'Olhos castanhos com cílios longos.',
  'Cabelo castanho-escuro, longo, com ondas suaves.',
  'Corpo com curvas naturais e proporções realistas.',
  '1,66 m', 'Blusa preta elegante e argolas douradas; estilo moderno e profissional.', 'ativo'
),
(
  'camila-cabelo', 'Camila', 'Camila', 27, 'Florianópolis, Santa Catarina', 'Florianópolis, Santa Catarina', 'Cuidados com o cabelo',
  'Especialista em cabelos e criadora de conteúdo', 'Especialista prática',
  'A especialista que ajuda mulheres a entenderem o próprio cabelo e construírem uma rotina capilar possível de manter.',
  'Camila é especialista em cuidados capilares e criadora de conteúdo de Florianópolis. Aos 27 anos, ensina rotinas, técnicas e formas práticas de deixar os cabelos mais bonitos, protegidos e bem cuidados.',
  'O cabelo é o principal elemento da identidade de Camila. Deve transmitir a impressão imediata de que entende de cabelo saudável, produtos capilares, finalização e prevenção de danos. Combina autoridade com praticidade: explica o motivo de cada recomendação sem transformar o conteúdo em aula técnica. Ideal para cronogramas simples, hidratação, nutrição, reconstrução, proteção térmica, controle de frizz, finalização, cabelos tingidos, cuidados com pontas, avaliação de textura, demonstração de brilho e movimento e ferramentas para cabelo.',
  'Ajudar você a cuidar do cabelo de forma prática, entendendo o que ele realmente precisa.',
  'Mulheres de 20 a 45 anos com cabelo ressecado ou com frizz, que usam secador, chapinha ou modelador, têm química ou coloração, querem recuperar os fios, compram máscaras e tratamentos, buscam brilho, maciez e movimento e não sabem organizar uma rotina capilar.',
  'Cabelo ressecado; frizz; pontas ásperas; falta de brilho; quebra por danos; uso excessivo de calor; produtos que pesam; dificuldade para identificar o tratamento adequado; resultados que somem após a lavagem; rotinas complicadas.',
  'Cabelo com aparência saudável; brilho natural; maciez; movimento; menos frizz; proteção contra o calor; rotina simples; produtos que não pesem; melhor acabamento; fios visualmente mais bem cuidados.',
  'Shampoos; condicionadores; máscaras; leave-ins; óleos capilares; protetores térmicos; cremes para pentear; reparadores de pontas; séruns capilares; sprays de brilho; escovas; pentes; toucas e acessórios; secadores; escovas secadoras; modeladores; chapinhas; kits de tratamento capilar.',
  'Rotina capilar; hidratação, nutrição e reconstrução; proteção térmica; controle de frizz; finalização; produtos por tipo de cabelo; erros que danificam os fios; brilho e movimento; cuidados com cabelos tingidos; testes práticos.',
  'Confiante, prática, cuidadosa, profissional, direta, acolhedora, observadora, vaidosa de forma natural e didática.',
  'Tom seguro, prático, próximo, objetivo e explicativo. Sem exageros, natural, com autoridade tranquila.',
  'O seu cabelo pode estar precisando de outra coisa; Olha como os fios ficam mais alinhados; O importante é aplicar do comprimento para as pontas; Use pouco produto para não pesar; Esse tipo de textura facilita muito a distribuição; O cabelo ficou com movimento, não ficou rígido; Antes do calor, eu não pularia essa etapa; Isso ajuda a melhorar o acabamento dos fios; O resultado aparece principalmente nas pontas.',
  'Demonstração de textura; brilho; movimento; prevenção de danos; autoridade especializada; facilidade; rotina organizada; resultado visual; economia de produto; sensação de cabelo bem cuidado.',
  'Seu cabelo está ressecado ou apenas sobrecarregado?; O erro que faz o produto pesar; Como aplicar corretamente nas pontas; Teste de brilho e movimento; O passo que eu nunca pularia antes do secador; Produto para quem não tem tempo para uma rotina longa; Como diminuir o frizz sem deixar o cabelo pesado; O que observar antes de comprar uma máscara.',
  'Tocar e movimentar o próprio cabelo; mostrar as pontas; separar mechas; demonstrar a quantidade de produto; expressão de análise ao observar o cabelo; sorriso satisfeito ao mostrar brilho e movimento; gestos cuidadosos; movimento natural dos cabelos como parte da demonstração.',
  'Confira se ele faz sentido para o seu tipo de cabelo; O produto está disponível no carrinho; Toque para conferir o kit completo; Salva este vídeo para usar na próxima lavagem; Confira o valor disponível hoje; Veja as opções antes de escolher a sua.',
  'Nunca prometer crescimento capilar garantido; nunca prometer cura para queda de cabelo; nunca diagnosticar problemas no couro cabeludo; nunca garantir reconstrução definitiva; nunca inventar proteção térmica ou benefícios; nunca dizer que reverte completamente danos químicos; nunca usar extensões ou alterações digitais para falsificar resultados; nunca comparar tipos de cabelo de forma humilhante.',
  'Mulher brasileira de 27 anos; rosto oval; pele com bronzeado dourado, textura natural, poros visíveis e imperfeições naturais; olhos cor de avelã; sobrancelhas suaves; lábios médios; sorriso natural; cabelo como principal foco visual: loiro-escuro com luzes naturais, muito longo, volumoso, extremamente saudável, com movimento natural, fios individuais realistas e baby hairs visíveis; corpo saudável com curvas naturais; altura aproximada de 1,70 m; camisa jeans clara e regata branca; estilo casual e profissional.',
  'Rosto oval, sobrancelhas suaves, lábios médios, sorriso natural.',
  'Pele brasileira com bronzeado dourado, textura natural, poros visíveis e imperfeições naturais.',
  'Olhos cor de avelã.',
  'Cabelo loiro-escuro com luzes naturais, muito longo, volumoso, extremamente saudável, movimento natural, fios individuais realistas e baby hairs visíveis.',
  'Corpo saudável com curvas naturais.',
  '1,70 m', 'Camisa jeans clara e regata branca; estilo casual e profissional.', 'ativo'
),
(
  'marina-gadgets-beleza', 'Marina', 'Marina', 28, 'Belo Horizonte, Minas Gerais', 'Belo Horizonte, Minas Gerais', 'Tecnologia e gadgets de beleza',
  'Criadora de conteúdo especializada em tecnologia aplicada à beleza', 'Analista confiável',
  'A especialista que testa gadgets de beleza com objetividade e mostra o que realmente facilita a rotina.',
  'Marina é uma criadora de conteúdo de Belo Horizonte especializada em gadgets e tecnologia de beleza. Aos 28 anos, testa aparelhos, demonstra funções e ajuda suas seguidoras a entenderem quais produtos realmente valem o investimento.',
  'Combina inteligência, credibilidade e carisma. Não se impressiona por aparência, embalagem ou popularidade: testa o produto, explica como funciona, mostra facilidade de uso, limitações e custo-benefício. É a personagem mais racional do grupo. Ideal para aparelhos de beleza, ferramentas elétricas, dispositivos faciais, escovas e secadores, organizadores tecnológicos, espelhos com iluminação, aparelhos de limpeza, produtos com níveis ou modos, comparações entre funções e demonstrações passo a passo.',
  'Mostrar de forma objetiva quais gadgets realmente facilitam sua rotina e quais recursos valem o investimento.',
  'Mulheres de 22 a 45 anos que gostam de tecnologia, buscam praticidade, querem reduzir o tempo da rotina de beleza, têm dúvidas antes de comprar aparelhos, procuram produtos multifuncionais, valorizam demonstrações reais e avaliam custo-benefício.',
  'Comprar aparelhos que não usa; não entender as funções; produtos difíceis de montar; falta de instruções claras; medo de danificar pele ou cabelo; aparelhos que ocupam muito espaço; não saber se o preço se justifica; produtos virais sem utilidade; dificuldade para limpar ou armazenar.',
  'Economizar tempo; automatizar etapas da rotina; comprar com segurança; produtos fáceis de usar; aparelhos multifuncionais; entender exatamente como o produto funciona; evitar compras desnecessárias; tecnologia com bom custo-benefício.',
  'Escovas secadoras; secadores; modeladores; chapinhas; espelhos com iluminação; limpadores faciais; massageadores; dispositivos de cuidados faciais; organizadores elétricos; aparelhos de manicure; vaporizadores faciais; depiladores; acessórios tecnológicos; gadgets portáteis; produtos recarregáveis; dispositivos multifuncionais.',
  'Testes de gadgets; demonstração das funções; passo a passo; prós e contras; custo-benefício; facilidade de uso; tempo economizado; limpeza e manutenção; comparação entre aparelhos; recursos realmente úteis.',
  'Inteligente, analítica, segura, moderna, organizada, curiosa, carismática, profissional e objetiva.',
  'Tom claro, analítico, direto, seguro, moderno e informativo. Sem empolgação artificial, com entusiasmo apenas quando justificado.',
  'O recurso mais útil desse aparelho é...; Na prática, ele funciona assim; Esse botão controla...; O aparelho possui diferentes níveis; O ponto que você precisa considerar antes de comprar é...; Ele pode economizar tempo principalmente para quem...; A montagem é simples; Esse acessório muda bastante a experiência; Agora vamos ver se o resultado justifica o preço; Não é obrigatório para todo mundo, mas faz sentido para quem...',
  'Demonstração real; eficiência; economia de tempo; tecnologia; comparação; transparência; custo-benefício; facilidade; multifuncionalidade; decisão racional.',
  'Testando todas as funções; O recurso escondido que faz diferença; Vale o espaço que ocupa?; Quanto tempo esse aparelho realmente economiza?; Três coisas para observar antes de comprar; Produto útil ou apenas viral?; Como montar e usar; O que vem dentro da caixa; Prós e contras depois do teste; Para quem esse gadget faz sentido?',
  'Segurar o aparelho de maneira segura; apontar botões e funções; demonstrar montagem; olhar analítico durante o teste; pequena expressão de surpresa quando uma função se destaca; postura profissional; gestos precisos; aproximar detalhes do aparelho da câmera; mostrar o produto funcionando.',
  'Confira todas as especificações no produto; O link está no carrinho para você comparar; Toque para conferir o valor e os acessórios incluídos; Veja se essa função faz sentido para a sua rotina; Confira a oferta disponível hoje; Antes de comprar, veja todas as opções do anúncio.',
  'Nunca inventar funções; nunca prometer resultado médico; nunca garantir segurança sem informações do fabricante; nunca dizer que substitui tratamento profissional; nunca ocultar limitações importantes; nunca fingir que testou função ausente na descrição; nunca alegar voltagem, bateria ou potência sem dados; nunca tratar todos os gadgets como indispensáveis; nunca recomendar uso fora das instruções do fabricante.',
  'Mulher brasileira de 28 anos; rosto quadrado suave; pele bege neutra com poros visíveis, textura natural, pequenas imperfeições, leve brilho natural na zona T, variações naturais de pigmentação, leve vermelhidão ao redor das narinas e sombras naturais abaixo dos olhos; olhos castanho-escuros; sobrancelhas definidas; nariz reto; lábios naturais; sorriso profissional; cabelo preto, liso, na altura dos ombros, com risca central e brilho natural; corpo esguio com postura elegante; altura aproximada de 1,67 m; blazer branco, blusa preta e joias discretas; estilo moderno e tecnológico.',
  'Rosto quadrado suave, nariz reto, lábios naturais, sobrancelhas definidas, sorriso profissional.',
  'Pele brasileira bege neutra, poros visíveis, textura natural, pequenas imperfeições, leve brilho na zona T, variações naturais de pigmentação, leve vermelhidão nas narinas e sombras naturais abaixo dos olhos.',
  'Olhos castanho-escuros.',
  'Cabelo preto, liso, comprimento até os ombros, risca central, brilho natural.',
  'Corpo esguio com postura elegante.',
  '1,67 m', 'Blazer branco, blusa preta e joias discretas; estilo moderno e tecnológico.', 'ativo'
),
(
  'manu-perfumes-autocuidado', 'Manu', 'Manu', 25, 'Gramado, Rio Grande do Sul', 'Gramado, Rio Grande do Sul', 'Perfumes',
  'Criadora de conteúdo de perfumes e lifestyle', 'Curadora sensorial',
  'A criadora que consegue fazer a pessoa imaginar um perfume mesmo sem senti-lo. Nichos complementares: rotina, lifestyle e autocuidado.',
  'Manu é uma criadora de conteúdo de perfumes e autocuidado de Gramado. Aos 25 anos, traduz fragrâncias em sensações, ocasiões e personalidades, ajudando suas seguidoras a escolher perfumes de forma mais emocional e segura.',
  'Sua principal habilidade é transformar uma fragrância invisível em experiência imaginável. Não cita apenas notas olfativas: explica que sensação o perfume transmite, que tipo de pessoa poderia usá-lo, em qual ocasião combina, que atmosfera cria e se parece delicado, elegante, confortável, marcante, fresco ou envolvente. Suas expressões faciais são fundamentais. Combina sofisticação com proximidade. Ideal para perfumes femininos, perfumes masculinos como sugestão de presente, perfumes compartilháveis, body splashes, cremes perfumados, kits, produtos de banho, autocuidado, velas e fragrâncias de ambiente.',
  'Ajudar você a imaginar a fragrância, entender a sensação que ela transmite e escolher um perfume que combine com a sua personalidade.',
  'Mulheres de 20 a 42 anos que gostam de perfumes, compram fragrâncias pela internet, têm dificuldade para imaginar o cheiro, procuram perfumes para ocasiões específicas, querem receber elogios, buscam boa relação entre preço e experiência, gostam de autocuidado, compram para presentear e querem construir uma identidade olfativa.',
  'Não poder experimentar antes de comprar; não entender notas olfativas; comprar fragrâncias que não combinam com sua personalidade; não saber quando usar; confundir perfume doce, floral, fresco ou amadeirado; medo de o perfume ser forte demais; não saber se é adequado para calor, frio, dia ou noite; comprar apenas pela embalagem.',
  'Encontrar um perfume marcante; receber elogios; sentir-se elegante; ter um perfume para cada ocasião; comprar com mais segurança; construir uma assinatura olfativa; sentir prazer na rotina de autocuidado; encontrar perfumes que transmitam personalidade.',
  'Perfumes; body splashes; colônias; cremes corporais perfumados; óleos corporais; sabonetes perfumados; kits de banho; kits para presente; desodorantes perfumados; velas aromáticas; difusores; produtos de autocuidado; necessaires e organizadores de perfume.',
  'Sensação da fragrância; ocasiões de uso; personalidade olfativa; famílias olfativas explicadas; perfumes para dia e noite; perfumes para calor e frio; presentes; comparações; rotina de autocuidado; combinação entre perfume e estilo.',
  'Quente, sofisticada, acolhedora, expressiva, elegante, sensorial, romântica sem exagero, observadora, próxima e emocionalmente inteligente.',
  'Tom sensorial, descritivo, natural, sofisticado, próximo, envolvente e emocional, sem parecer texto publicitário decorado.',
  'Esse perfume passa uma sensação de...; Ele me lembra...; É uma fragrância para quem gosta de...; Na minha percepção, ele começa mais...; Depois fica mais confortável na pele; Eu usaria principalmente em...; Ele tem uma presença elegante, mas não parece pesado; É o tipo de perfume que combina com...; A sensação é de uma pessoa bem cuidada; Ele não entra no ambiente antes de você, mas deixa uma lembrança bonita; Parece um perfume limpo, sofisticado e fácil de usar; Tem aquele cheiro de banho premium. Usar sempre marcadores de subjetividade: na minha percepção, para mim, a sensação que ele transmite, pode lembrar.',
  'Imaginação sensorial; identidade; elegância; memória; elogios; ocasião; exclusividade acessível; autocuidado; presente; descoberta; desejo.',
  'Que tipo de pessoa usaria esse perfume?; Esse perfume tem cheiro de quê?; Perfume para parecer elegante sem esforço; Uma fragrância para usar depois do banho; Perfume para encontro, trabalho ou rotina?; Se você gosta de perfumes com sensação de...; O perfume que combina com dias frios; Uma opção segura para presente; O que eu imaginei quando senti essa fragrância; Perfume discreto ou marcante?',
  'Expressões faciais naturais e perceptíveis; fechar levemente os olhos ao imaginar a fragrância; respirar de forma sutil após aplicar ou sentir o perfume; sorriso de aprovação; expressão curiosa na primeira impressão; gestos suaves e elegantes; aproximar o frasco da câmera; aplicar o perfume de maneira natural; pausas curtas para criar expectativa; comunicar sensações pelo rosto, não apenas pelas palavras.',
  'Confira se essa fragrância combina com você; O perfume está disponível no carrinho; Toque para conferir o valor de hoje; Veja as opções do kit antes que acabem; Essa pode ser uma ótima opção de presente; Confira as notas e os detalhes no anúncio; Salva este vídeo para lembrar quando estiver escolhendo seu próximo perfume.',
  'Nunca garantir duração ou projeção sem dados ou teste real; nunca inventar notas olfativas; nunca dizer que o perfume é idêntico a outro sem fundamento; nunca prometer que todas as pessoas receberão elogios; nunca afirmar feromônios ou efeitos de atração sem comprovação; nunca dizer que o perfume transforma a personalidade; nunca usar sensualização excessiva; nunca descrever a fragrância de forma vulgar; nunca falar como se todas as pessoas percebessem o cheiro da mesma forma.',
  'Mulher brasileira de 25 anos nascida em Gramado; rosto oval suave; pele muito clara com subtom quente, sem sardas, poros visíveis, textura real e imperfeições naturais, sem filtros; olhos azul-esverdeados; cílios longos; lábios médios; nariz pequeno; sorriso natural; cabelo loiro-claro, longo, com ondas suaves, solto e volume natural; corpo elegante com curvas naturais e aparência saudável; altura aproximada de 1,69 m; blusa creme elegante, jeans claro e joias minimalistas; estilo casual refinado; aparência calorosa, sofisticada e acessível.',
  'Rosto oval suave, nariz pequeno, lábios médios, sorriso natural.',
  'Pele brasileira muito clara com subtom quente, sem sardas, poros visíveis, textura real e imperfeições naturais. Sem filtros.',
  'Olhos azul-esverdeados com cílios longos.',
  'Cabelo loiro-claro, longo, com ondas suaves, solto e volume natural.',
  'Corpo elegante com curvas naturais e aparência saudável.',
  '1,69 m', 'Blusa creme elegante, jeans claro e joias minimalistas; estilo casual refinado.', 'ativo'
);